name: Daily Python Script

on:
  schedule:
    - cron: '59 7 * * *'  # Runs at 7:59 AM UTC (GMT) every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Make script executable
      run: chmod +x ./FinalVersion.py

    - name: Run Python script
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      run: ./FinalVersion.py

